#ifndef CHAT_CLI_OP_H_
#define CHAT_CLI_OP_H_

#define BT_MESH_CHAT_CLI_OP_MESSAGE           BT_MESH_MODEL_OP_3(0x00, 0xFFFF)
#define BT_MESH_CHAT_CLI_OP_PRIVATE_MESSAGE   BT_MESH_MODEL_OP_3(0x01, 0xFFFF)
#define BT_MESH_CHAT_CLI_OP_MESSAGE_REPLY     BT_MESH_MODEL_OP_3(0x02, 0xFFFF)
#define BT_MESH_CHAT_CLI_OP_PRESENCE          BT_MESH_MODEL_OP_3(0x03, 0xFFFF)
#define BT_MESH_CHAT_CLI_OP_PRESENCE_GET      BT_MESH_MODEL_OP_3(0x04, 0xFFFF)

/* Message lengths */
#define BT_MESH_CHAT_CLI_MSG_LEN_MESSAGE_REPLY    0
#define BT_MESH_CHAT_CLI_MSG_LEN_PRESENCE         1
#define BT_MESH_CHAT_CLI_MSG_LEN_PRESENCE_GET     0
#define BT_MESH_CHAT_CLI_MSG_MINLEN_MESSAGE       2
#define BT_MESH_CHAT_CLI_MSG_MAXLEN_MESSAGE       32

#endif /* CHAT_CLI_OP_H_ */
